services:
  trade-shield-backend:
    build: ../
    image: trade-shield-image:latest
    container_name: trade-shield-backend
    restart: always
    volumes:
      - ../:/home/TadeShield
    working_dir: /home/TadeShield
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST:         ${REDIS_HOST}
      REDIS_PORT:         ${REDIS_PORT}
      POSTGRES_HOST:      ${POSTGRES_HOST}
      POSTGRES_PORT:      ${POSTGRES_PORT}
      POSTGRES_DATABASE:  ${POSTGRES_DB}
      POSTGRES_USER:      ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000

